<a href="https://colab.research.google.com/github/fathanick/NLP-Course-UII/blob/master/Char_level.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Source: https://machinelearningmastery.com/develop-character-based-neural-language-model-keras/

###Load and View Data

In [0]:
def load_file(filename):
  f = open(filename,'r')
  txt = f.read()
  f.close()

  return txt

In [2]:
myfile = "/content/drive/My Drive/PYTHON CODE OF MINE/sample-text.txt"
my_text = load_file(myfile)
print(my_text)

Ledakan bintang raksasa alias supernova yang dikenal dengan nama SN2016aps dicatat sebagai supernova paling cerah yang pernah diamati astronom. Supernova ini terjadi di galaksi yang berjarak 3,6 miliar tahun cahaya dari Bumi.
Penemuan ini diungkap oleh astronom dari Center for Astrophysics yang dimuat dalam jurnal Nature. Saking cerahnya, supernova ini bahkan mengalahkan galaksinya sendiri.
"Di supernova pada umumnya, radiasinya kurang dari 1% dari energi total," kata penulis utama studi ini, Matt Nicholl dari University of Birmingham dalam keterangannya yang dikutip detikINET dari Space, Rabu (15/4/2020).



###Clean Text

In [3]:
tokens = my_text.split()
my_text = ' '.join(tokens)
my_text

'Ledakan bintang raksasa alias supernova yang dikenal dengan nama SN2016aps dicatat sebagai supernova paling cerah yang pernah diamati astronom. Supernova ini terjadi di galaksi yang berjarak 3,6 miliar tahun cahaya dari Bumi. Penemuan ini diungkap oleh astronom dari Center for Astrophysics yang dimuat dalam jurnal Nature. Saking cerahnya, supernova ini bahkan mengalahkan galaksinya sendiri. "Di supernova pada umumnya, radiasinya kurang dari 1% dari energi total," kata penulis utama studi ini, Matt Nicholl dari University of Birmingham dalam keterangannya yang dikutip detikINET dari Space, Rabu (15/4/2020).'

###Create Sequences

In [4]:
length = 10
seq = list()

for i in range(length, len(my_text)):
  sq = my_text[i-length:i+1]
  seq.append(sq)
print("Total sequences: %d" % len(seq))

Total sequences: 603


###Save Sequences

In [0]:
def save_file(lines, filename):
  data = '\n'.join(lines)
  file = open(filename,'w')
  file.write(data)
  file.close()

In [0]:
output_file = '/content/drive/My Drive/PYTHON CODE OF MINE/char_seq.txt'
save_file(seq, output_file)

###Train Language Model


####Load Data

In [0]:
char_file = '/content/drive/My Drive/PYTHON CODE OF MINE/char_seq.txt'
raw_txt = load_file(char_file)
lines = raw_txt.split('\n')
#print(lines)

####Encode Sequences

In [0]:
chars = sorted(list(set(raw_txt)))
mapping = dict((c,i) for i, c in enumerate(chars))
#print(chars)
#print(mapping)

In [9]:
seq = list()

for line in lines:
  #integer encode line
  encoded_seq = [mapping[char] for char in line]
  #store
  seq.append(encoded_seq)

print(seq)

[[22, 34, 33, 30, 40, 30, 43, 1, 31, 38, 43], [34, 33, 30, 40, 30, 43, 1, 31, 38, 43, 48], [33, 30, 40, 30, 43, 1, 31, 38, 43, 48, 30], [30, 40, 30, 43, 1, 31, 38, 43, 48, 30, 43], [40, 30, 43, 1, 31, 38, 43, 48, 30, 43, 36], [30, 43, 1, 31, 38, 43, 48, 30, 43, 36, 1], [43, 1, 31, 38, 43, 48, 30, 43, 36, 1, 46], [1, 31, 38, 43, 48, 30, 43, 36, 1, 46, 30], [31, 38, 43, 48, 30, 43, 36, 1, 46, 30, 40], [38, 43, 48, 30, 43, 36, 1, 46, 30, 40, 47], [43, 48, 30, 43, 36, 1, 46, 30, 40, 47, 30], [48, 30, 43, 36, 1, 46, 30, 40, 47, 30, 47], [30, 43, 36, 1, 46, 30, 40, 47, 30, 47, 30], [43, 36, 1, 46, 30, 40, 47, 30, 47, 30, 1], [36, 1, 46, 30, 40, 47, 30, 47, 30, 1, 30], [1, 46, 30, 40, 47, 30, 47, 30, 1, 30, 41], [46, 30, 40, 47, 30, 47, 30, 1, 30, 41, 38], [30, 40, 47, 30, 47, 30, 1, 30, 41, 38, 30], [40, 47, 30, 47, 30, 1, 30, 41, 38, 30, 47], [47, 30, 47, 30, 1, 30, 41, 38, 30, 47, 1], [30, 47, 30, 1, 30, 41, 38, 30, 47, 1, 47], [47, 30, 1, 30, 41, 38, 30, 47, 1, 47, 49], [30, 1, 30, 41, 38

In [10]:
#vocab size
vocab_size = len(mapping)
print("Vocabulary size: %d" % vocab_size)

Vocabulary size: 52


####Split Inputs and Output

In [0]:
from numpy import array

seq = array(seq)
X,y = seq[:,:-1], seq[:,-1]

####One Hot Encode

In [12]:
from keras.utils import to_categorical

seq = [to_categorical(x, num_classes = vocab_size) for x in X]
X = array(seq)
y = to_categorical(y, num_classes = vocab_size)
print(X)
print(y)

Using TensorFlow backend.


[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 1. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 1. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
[[0. 0. 0.

####Fit Model

In [13]:
from keras.models import Sequential
from keras.layers import Dense, LSTM
#define model

model = Sequential()
model.add(LSTM(64, input_shape=(X.shape[1], X.shape[2])))
model.add(Dense(vocab_size, activation = 'softmax'))
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 64)                29952     
_________________________________________________________________
dense_1 (Dense)              (None, 52)                3380      
Total params: 33,332
Trainable params: 33,332
Non-trainable params: 0
_________________________________________________________________
None


In [14]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=100, verbose=2)

Epoch 1/100
 - 1s - loss: 3.8949 - accuracy: 0.1177
Epoch 2/100
 - 0s - loss: 3.5256 - accuracy: 0.1791
Epoch 3/100
 - 0s - loss: 3.1511 - accuracy: 0.1459
Epoch 4/100
 - 0s - loss: 3.0988 - accuracy: 0.1376
Epoch 5/100
 - 0s - loss: 3.0754 - accuracy: 0.1360
Epoch 6/100
 - 0s - loss: 3.0567 - accuracy: 0.1758
Epoch 7/100
 - 0s - loss: 3.0343 - accuracy: 0.1725
Epoch 8/100
 - 0s - loss: 3.0233 - accuracy: 0.1625
Epoch 9/100
 - 0s - loss: 3.0038 - accuracy: 0.1907
Epoch 10/100
 - 0s - loss: 2.9936 - accuracy: 0.2106
Epoch 11/100
 - 0s - loss: 2.9692 - accuracy: 0.2040
Epoch 12/100
 - 0s - loss: 2.9627 - accuracy: 0.2139
Epoch 13/100
 - 0s - loss: 2.9343 - accuracy: 0.2073
Epoch 14/100
 - 0s - loss: 2.9090 - accuracy: 0.2206
Epoch 15/100
 - 0s - loss: 2.8940 - accuracy: 0.2255
Epoch 16/100
 - 0s - loss: 2.8632 - accuracy: 0.2090
Epoch 17/100
 - 0s - loss: 2.8412 - accuracy: 0.2123
Epoch 18/100
 - 0s - loss: 2.8136 - accuracy: 0.2206
Epoch 19/100
 - 0s - loss: 2.7939 - accuracy: 0.2189
Ep

####Save Model

In [0]:
from pickle import dump
#save the model
model.save('/content/drive/My Drive/PYTHON CODE OF MINE/model.h5')

#save the mapping
dump(mapping, open('/content/drive/My Drive/PYTHON CODE OF MINE/mapping.pkl','wb'))

###Generate Text

In [0]:
from keras.models import load_model
from pickle import load

model = load_model('/content/drive/My Drive/PYTHON CODE OF MINE/model.h5')
mapping = load(open('/content/drive/My Drive/PYTHON CODE OF MINE/mapping.pkl','rb'))

In [28]:
from pickle import load
from keras.models import load_model
from keras.utils import to_categorical
from keras.preprocessing.sequence import pad_sequences

# generate a sequence of characters with a language model
def generate_seq(model, mapping, seq_length, seed_text, n_chars):
	in_text = seed_text
	# generate a fixed number of characters
	for _ in range(n_chars):
		# encode the characters as integers
		encoded = [mapping[char] for char in in_text]
		# truncate sequences to a fixed length
		encoded = pad_sequences([encoded], maxlen=seq_length, truncating='pre')
		# one hot encode
		encoded = to_categorical(encoded, num_classes=len(mapping))
		#print(encoded.shape[1])
		#encoded = encoded.reshape(1, encoded.shape[0], encoded.shape[1])
		# predict character
		yhat = model.predict_classes(encoded, verbose=0)
		# reverse map integer to character
		out_char = ''
		for char, index in mapping.items():
			if index == yhat:
				out_char = char
				break
		# append to input
		in_text += char
	return in_text

model = load_model('/content/drive/My Drive/PYTHON CODE OF MINE/model.h5')
mapping = load(open('/content/drive/My Drive/PYTHON CODE OF MINE/mapping.pkl','rb'))

# test start of rhyme
print(generate_seq(model, mapping, 10, 'bintang raksa', 20))
# test mid-line
print(generate_seq(model, mapping, 10, 'kenal dengan na', 20))
# test not in original
print(generate_seq(model, mapping, 10, 'bintang Supernov', 20))

bintang raksasa alias supernova p
kenal dengan nama SN2016aps dicatat
bintang Supernova ini bahkan mengala
